#!/bin/bash
# =============================================================================
# Stage 04 — Base system build
# -----------------------------------------------------------------------------
# Builds the DXN1-OS root userland against the stage 02 toolchain and installs
# it into ${DXN1_ROOTFS}. This mirrors LFS chapters 7–8 (the "temporal → final"
# system construction), then chroots into the result for the second half where
# the build is done natively with the just-built gcc.
#
# Output:
#   ${DXN1_ROOTFS}/bin/bash               A working shell
#   ${DXN1_ROOTFS}/usr/bin/{coreutils..}  Base utilities
#   ${DXN1_ROOTFS}/etc/{fstab,passwd,…}   Skeleton config
#   ${DXN1_ROOTFS}/sbin/init              → /bin/bash rc-based PID 1
#
# Packages built here are read from config/packages.list, filtered to those
# tagged as "base system" (see below). Driver packages come in stage 05.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/config/environment"

if [[ -t 2 ]]; then
    C_R=$'\033[31m'; C_G=$'\033[32m'; C_Y=$'\033[33m'; C_B=$'\033[34m'; C_0=$'\033[0m'
else C_R=""; C_G=""; C_Y=""; C_B=""; C_0=""; fi
log()     { printf '%s[%s]%s %s\n'  "${C_B}" "$(date +%H:%M:%S)" "${C_0}" "$*"; }
success() { printf '%s✓ %s%s%s\n'   "${C_G}" "$*" "${C_0}"; }
warn()    { printf '%s! %s%s%s\n'   "${C_Y}" "$*" "${C_0}" >&2; }
die()     { printf '%s✗ %s%s%s\n'   "${C_R}" "$*" "${C_0}" >&2; exit 1; }
trap 'die "Stage 04 aborted at line $LINENO (exit $?)"' ERR

# ---------------------------------------------------------------------------
# 1. Skeleton the rootfs directory tree.
# ---------------------------------------------------------------------------
log "Skeletoning rootfs at ${DXN1_ROOTFS}…"
for d in bin boot dev etc etc/opt home lib lib64 media mnt \
         opt proc root run sbin srv sys tmp usr var; do
    install -d -m 0755 "${DXN1_ROOTFS}/${d}"
done
install -d -m 0700 "${DXN1_ROOTFS}/root"
for d in bin include lib lib32 lib64 libexec sbin share src; do
    install -d -m 0755 "${DXN1_ROOTFS}/usr/${d}"
done
install -d -m 1777 "${DXN1_ROOTFS}/tmp" "${DXN1_ROOTFS}/var/tmp"
install -d -m 0755 "${DXN1_ROOTFS}/usr/local/"{bin,sbin,etc,lib,share}
install -d -m 0755 "${DXN1_ROOTFS}/var/"{cache,lib,local,lock,log,mail,opt,run,spool}
ln -sfn /run "${DXN1_ROOTFS}/var/run"
ln -sfn /run/lock "${DXN1_ROOTFS}/var/lock"
ln -sfn /run "${DXN1_ROOTFS}/etc/init.d" 2>/dev/null || true
success "Rootfs skeleton populated."

# ---------------------------------------------------------------------------
# 2. Skeleton system files (passwd, group, fstab, hostname, profile, os-release).
# ---------------------------------------------------------------------------
cat > "${DXN1_ROOTFS}/etc/passwd" <<'EOF'
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/usr/bin/false
daemon:x:2:2:daemon:/dev/null:/usr/bin/false
messagebus:x:18:18:D-Bus Message Daemon:/var/run/dbus:/usr/bin/false
sshd:x:51:51:sshd Privilege Separation:/var/empty:/usr/bin/false
lfs:x:1000:1000:DXN1-OS user:/home/lfs:/bin/bash
EOF
cat > "${DXN1_ROOTFS}/etc/group" <<'EOF'
root:x:0:
bin:x:1:
daemon:x:2:
sys:x:3:
tty:x:5:
disk:x:6:
audio:x:17:
messagebus:x:18:
input:x:24:
video:x:29:
sshd:x:51:
users:x:100:
lfs:x:1000:
EOF
cat > "${DXN1_ROOTFS}/etc/shadow" <<'EOF'
root:!:19000:0:99999:7:::
bin:*:19000:0:99999:7:::
daemon:*:19000:0:99999:7:::
lfs:!:19000:0:99999:7:::
EOF
chmod 0600 "${DXN1_ROOTFS}/etc/shadow"

cat > "${DXN1_ROOTFS}/etc/fstab" <<'EOF'
# Generated by DXN1-OS stage 04 — installer/post-install.sh will rewrite this.
# <fs>              <mount>    <type>   <opts>          <dump> <pass>
proc                /proc      proc     defaults         0      0
sysfs               /sys       sysfs    defaults         0      0
devtmpfs            /dev       devtmpfs mode=0755,nosuid 0      0
devpts              /dev/pts   devpts   gid=5,mode=620   0      0
tmpfs               /run       tmpfs    defaults,nosuid  0      0
tmpfs               /tmp       tmpfs    defaults,nosuid  0      0
LABEL=dxn1-root     /          ext4     defaults,noatime 0      1
LABEL=dxn1-swap     swap       swap     pri=1            0      0
EOF

echo "dxn1-os" > "${DXN1_ROOTFS}/etc/hostname"

cat > "${DXN1_ROOTFS}/etc/os-release" <<EOF
NAME="DXN1-OS"
VERSION="${LFS_VERSION} (${DXN1_CODENAME})"
ID=dxn1-os
ID_LIKE=lfs
VERSION_ID="${LFS_VERSION}"
PRETTY_NAME="DXN1-OS ${LFS_VERSION} (${DXN1_CODENAME})"
ANSI_COLOR="0;34"
HOME_URL="https://dxn1.org/"
BUG_REPORT_URL="https://dxn1.org/bugs/"
EOF

cat > "${DXN1_ROOTFS}/etc/profile" <<'EOF'
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export LC_ALL="${LC_ALL:-POSIX}"
export PS1='[\u@\h \W]\$ '
umask 022
EOF

# Network config skeleton.
install -d -m 0755 "${DXN1_ROOTFS}/etc/network"
cat > "${DXN1_ROOTFS}/etc/network/interfaces" <<'EOF'
# loopback
auto lo
iface lo inet loopback
# primary NIC — DHCP by default
auto eth0
iface eth0 inet dhcp
EOF

# Skeleton resolv.conf; the network service overrides at boot.
echo "nameserver 1.1.1.1" > "${DXN1_ROOTFS}/etc/resolv.conf"
chmod 0644 "${DXN1_ROOTFS}/etc/resolv.conf"

# Install init scripts (init/, services/) into the rootfs.
cp -a "${SCRIPT_DIR}/init/init"        "${DXN1_ROOTFS}/sbin/init"
cp -a "${SCRIPT_DIR}/init/rc.sysinit"  "${DXN1_ROOTFS}/etc/rc.d/rc.sysinit"
install -d -m 0755 "${DXN1_ROOTFS}/etc/init.d"
for svc in network udev sshd; do
    cp -a "${SCRIPT_DIR}/init/services/${svc}" "${DXN1_ROOTFS}/etc/init.d/${svc}"
done

# ----------------------------------------------------------------------------
# 3. Mount /dev /proc /sys /run into the rootfs and chroot to build natively.
# ----------------------------------------------------------------------------
log "Preparing chroot at ${DXN1_ROOTFS}…"
mount --bind /dev  "${DXN1_ROOTFS}/dev"
mount --bind /proc "${DXN1_ROOTFS}/proc"
mount --bind /sys  "${DXN1_ROOTFS}/sys"
mount -t tmpfs tmpfs "${DXN1_ROOTFS}/run"

# Copy the toolchain into the chroot so the build runs self-contained.
mkdir -p "${DXN1_ROOTFS}/tools"
mount --bind /tools "${DXN1_ROOTFS}/tools"

cleanup() {
    log "Tearing down chroot mounts…"
    for m in dev proc sys run tools; do
        umount -R "${DXN1_ROOTFS}/${m}" 2>/dev/null || true
    done
}
trap cleanup EXIT

# The native-build script runs *inside* the chroot. We hand-write it to disk
# first so it survives the chroot boundary.
cat > "${DXN1_ROOTFS}/tmp/native-build.sh" <<'EOF'
#!/bin/bash
set -euo pipefail
export PATH=/tools/bin:/usr/bin:/bin:/usr/sbin:/sbin
export LC_ALL=POSIX
export MAKEFLAGS="-j$(nproc)"
export PKGDIR=/usr/src
mkdir -p /var/log/dxn1 /usr/src

build_pkg() {
    local name="$1" version="$2"; shift 2
    local src="/usr/src/${name}-${version}"
    [[ -d "${src}" ]] || return 1
    local stamp="/var/lib/dxn1/state/sys-${name}.stamp"
    [[ -f "${stamp}" ]] && return 0
    echo "→ Building ${name}-${version}"
    cd "${src}"
    "$@" || { echo "FAILED: ${name}-${version}"; return 1; }
    date -Is > "${stamp}"
}
mkdir -p /var/lib/dxn1/state

# Stage-4 "base system" subset of packages.list. Each entry:
#   name version configure-cmd make-cmd install-cmd
build_pkg coreutils 9.5 \
    "./configure --prefix=/usr --enable-no-install-program=kill" \
    "make" "make install"
build_pkg bash 5.2.32 \
    "./configure --prefix=/usr --without-bash-malloc --with-installed-readline" \
    "make" "make install"
build_pkg util-linux 2.40.2 \
    "./configure --prefix=/usr --libdir=/usr/lib --without-python --without-systemd" \
    "make" "make install"
build_pkg e2fsprogs 1.47.1 \
    "./configure --prefix=/usr --libdir=/usr/lib --enable-elf-shlibs --disable-libblkid" \
    "make" "make install install-libs"
build_pkg procps-ng 4.0.4 \
    "./configure --prefix=/usr --disable-static --disable-kill" \
    "make" "make install"
build_pkg openssh 9.8p1 \
    "./configure --prefix=/usr --sysconfdir=/etc/ssh --with-privsep-path=/var/empty" \
    "make" "make install"
build_pkg dhcpcd 10.0.10 \
    "./configure --prefix=/usr --sysconfdir=/etc --dbdir=/var/lib/dhcpcd" \
    "make" "make install"
build_pkg parted 3.6 \
    "./configure --prefix=/usr --disable-static" \
    "make" "make install"
build_pkg grub 2.12 \
    "./configure --prefix=/usr --sbindir=/usr/sbin --disable-werror --disable-grub-emu-usb" \
    "make" "make install"
build_pkg dialog 1.3-20240307 \
    "./configure --prefix=/usr --with-ncursesw" \
    "make" "make install"

echo "Native base-system build OK."
EOF
chmod +x "${DXN1_ROOTFS}/tmp/native-build.sh"

log "Entering chroot to build the base system natively…"
chroot "${DXN1_ROOTFS}" /tools/bin/env -i \
    HOME=/root TERM="${TERM:-linux}" \
    PATH=/tools/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    /bin/bash --login +h /tmp/native-build.sh 2>&1 \
    | tee "${DXN1_LOG_DIR}/stage-04-native.log"

rm -f "${DXN1_ROOTFS}/tmp/native-build.sh"

# ----------------------------------------------------------------------------
# 4. Install the kernel + modules built in stage 03.
# ----------------------------------------------------------------------------
if [[ -f "${DXN1_KERNEL_DIR}/bzImage" ]]; then
    log "Installing kernel & modules into rootfs…"
    install -D -m 0644 "${DXN1_KERNEL_DIR}/bzImage"  "${DXN1_ROOTFS}/boot/vmlinuz-${LFS_VERSION}"
    install -D -m 0644 "${DXN1_KERNEL_DIR}/System.map" "${DXN1_ROOTFS}/boot/System.map-${LFS_VERSION}"
    install -D -m 0644 "${DXN1_KERNEL_DIR}/config"   "${DXN1_ROOTFS}/boot/config-${LFS_VERSION}"
    if [[ -f "${DXN1_KERNEL_DIR}/modules.tar.xz" ]]; then
        tar -xf "${DXN1_KERNEL_DIR}/modules.tar.xz" -C "${DXN1_ROOTFS}/"
    fi
    success "Kernel installed to ${DXN1_ROOTFS}/boot/"
fi

printf '%s\n' "$(date -Is)" > "${DXN1_STATE_DIR}/stage-04.done"
success "Stage 04 complete. Rootfs at ${DXN1_ROOTFS} ($(du -sh "${DXN1_ROOTFS}" | cut -f1))"
