#!/bin/bash
# =============================================================================
# Stage 06 — Install DXN1-OS to target disk
# -----------------------------------------------------------------------------
# Mounts the root partition created in stage 01, copies the stage 04 rootfs
# onto it, installs the GRUB bootloader (BIOS + UEFI), and writes a final
# /etc/fstab on the target. The resulting disk is bootable.
#
# Inputs (from ${DXN1_STATE_DIR}/disk-layout.env, written by stage 01):
#   DXN1_DISK         /dev/sdX
#   DXN1_ROOT_PART    /dev/sdXN
#   DXN1_SWAP_PART    /dev/sdXN
#   DXN1_BOOT_PART    /dev/sdXN (ESP / BIOS boot partition)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/config/environment"

if [[ -t 2 ]]; then
    C_R=$'\033[31m'; C_G=$'\033[32m'; C_Y=$'\033[33m'; C_B=$'\033[34m'; C_0=$'\033[0m'
else C_R=""; C_G=""; C_Y=""; C_B=""; C_0=""; fi
log()     { printf '%s[%s]%s %s\n'  "${C_B}" "$(date +%H:%M:%S)" "${C_0}" "$*"; }
success() { printf '%s✓ %s%s%s\n'   "${C_G}" "$*" "${C_0}"; }
warn()    { printf '%s! %s%s%s\n'   "${C_Y}" "$*" "${C_0}" >&2; }
die()     { printf '%s✗ %s%s%s\n'   "${C_R}" "$*" "${C_0}" >&2; exit 1; }
trap 'die "Stage 06 aborted at line $LINENO (exit $?)"' ERR

# ---------------------------------------------------------------------------
# Load disk layout from stage 01.
# ---------------------------------------------------------------------------
LAYOUT="${DXN1_STATE_DIR}/disk-layout.env"
[[ -f "${LAYOUT}" ]] || die "Stage 01 layout missing: ${LAYOUT}. Run stage 01 first."
# shellcheck disable=SC1090
source "${LAYOUT}"
[[ -n "${DXN1_ROOT_PART:-}" ]] || die "DXN1_ROOT_PART not set in layout."
[[ -b "${DXN1_ROOT_PART}"   ]] || die "Root partition missing: ${DXN1_ROOT_PART}"

TARGET_MNT="${DXN1_OUT}/target"
mkdir -p "${TARGET_MNT}"

# ---------------------------------------------------------------------------
# 1. Mount the root partition.
# ---------------------------------------------------------------------------
log "Mounting ${DXN1_ROOT_PART} at ${TARGET_MNT}…"
mountpoint -q "${TARGET_MNT}" || mount "${DXN1_ROOT_PART}" "${TARGET_MNT}"

cleanup() {
    log "Unmounting target…"
    for sub in dev proc sys run boot/efi boot; do
        umount -R "${TARGET_MNT}/${sub}" 2>/dev/null || true
    done
    umount -R "${TARGET_MNT}" 2>/dev/null || true
}
trap cleanup EXIT

# ---------------------------------------------------------------------------
# 2. Copy rootfs onto target. We use rsync so partial / re-runs are safe.
# ---------------------------------------------------------------------------
log "Copying rootfs → ${TARGET_MNT} (this may take a few minutes)…"
# Pre-create the top-level dirs so rsync --one-file-system behaves.
for d in dev proc sys run boot tmp; do
    install -d -m 0755 "${TARGET_MNT}/${d}"
done
rsync -aHAXx --delete \
    --exclude='/proc/*' --exclude='/sys/*' --exclude='/dev/*' \
    --exclude='/run/*'  --exclude='/tmp/*' --exclude='/boot/efi/*' \
    --exclude='/tools/*' \
    "${DXN1_ROOTFS}/" "${TARGET_MNT}/"
success "Rootfs copied ($(du -sh "${TARGET_MNT}" 2>/dev/null | cut -f1))."

# ---------------------------------------------------------------------------
# 3. Write a real /etc/fstab based on the disk layout.
# ---------------------------------------------------------------------------
log "Writing /etc/fstab on target…"
ROOT_UUID=$(blkid -s UUID -o value "${DXN1_ROOT_PART}" 2>/dev/null || true)
SWAP_UUID=""
if [[ -n "${DXN1_SWAP_PART:-}" ]] && [[ -b "${DXN1_SWAP_PART}" ]]; then
    SWAP_UUID=$(blkid -s UUID -o value "${DXN1_SWAP_PART}" 2>/dev/null || true)
fi

cat > "${TARGET_MNT}/etc/fstab" <<EOF
# /etc/fstab — generated by DXN1-OS stage 06 ($(date -Is))
# <fs>                          <mount>    <type>  <opts>                    <dump> <pass>
UUID=${ROOT_UUID}               /          ext4    defaults,noatime          0      1
proc                            /proc      proc    defaults                  0      0
sysfs                           /sys       sysfs   defaults                  0      0
devtmpfs                        /dev       devtmpfs mode=0755,nosuid          0      0
devpts                          /dev/pts   devpts  gid=5,mode=620            0      0
tmpfs                           /run       tmpfs   defaults,nosuid,nodev     0      0
tmpfs                           /tmp       tmpfs   defaults,nosuid,nodev     0      0
EOF
if [[ -n "${SWAP_UUID}" ]]; then
    echo "UUID=${SWAP_UUID}               swap       swap    pri=1                     0      0" \
        >> "${TARGET_MNT}/etc/fstab"
fi
chmod 0644 "${TARGET_MNT}/etc/fstab"
success "fstab written."

# ---------------------------------------------------------------------------
# 4. Install the bootloader (BIOS grub-install + UEFI shim if present).
# ---------------------------------------------------------------------------
log "Installing GRUB bootloader on ${DXN1_DISK}…"

# Bind-mount pseudo filesystems into the target so grub-install works inside
# a chroot.
for sub in dev proc sys run; do
    mount --bind "/${sub}" "${TARGET_MNT}/${sub}"
done

# Stage 1: install to the MBR / ESP.
if [[ -n "${DXN1_BOOT_PART:-}" ]] && [[ -b "${DXN1_BOOT_PART}" ]]; then
    install -d -m 0755 "${TARGET_MNT}/boot/efi"
    mount "${DXN1_BOOT_PART}" "${TARGET_MNT}/boot/efi" 2>/dev/null || true
fi

# Detect whether to do BIOS or UEFI install. Default to BIOS unless /sys/firmware/efi exists.
if [[ -d /sys/firmware/efi ]]; then
    log "Installing GRUB (UEFI)…"
    chroot "${TARGET_MNT}" /usr/sbin/grub-install \
        --target=x86_64-efi \
        --efi-directory=/boot/efi \
        --bootloader-id=DXN1-OS \
        --recheck 2>&1 | tee "${DXN1_LOG_DIR}/stage-06-grub-uefi.log"
else
    log "Installing GRUB (BIOS)…"
    chroot "${TARGET_MNT}" /usr/sbin/grub-install \
        --target=i386-pc \
        --boot-directory=/boot \
        "${DXN1_DISK}" 2>&1 | tee "${DXN1_LOG_DIR}/stage-06-grub-bios.log"
fi

# Stage 2: write grub.cfg.
log "Generating grub.cfg…"
KVER=$(ls "${TARGET_MNT}/lib/modules" 2>/dev/null | head -n1 || echo "${LFS_VERSION}")
ROOT_LINE="UUID=${ROOT_UUID}"
cat > "${TARGET_MNT}/boot/grub/grub.cfg" <<EOF
# Auto-generated by DXN1-OS stage 06.
set default=0
set timeout=5

insmod part_gpt
insmod ext2
insmod fat

serial --unit=0 --speed=115200
terminal_input serial console
terminal_output serial console

menuentry "DXN1-OS ${LFS_VERSION} (${KVER})" {
    set root='$(grub-probe "${TARGET_MNT}" --target=fs_uuid 2>/dev/null || echo "${ROOT_UUID}")'
    linux /boot/vmlinuz-${KVER} root=${ROOT_LINE} rw quiet rootwait net.ifnames=0
}

menuentry "DXN1-OS ${LFS_VERSION} (recovery, no modeset)" {
    set root='$(grub-probe "${TARGET_MNT}" --target=fs_uuid 2>/dev/null || echo "${ROOT_UUID}")'
    linux /boot/vmlinuz-${KVER} root=${ROOT_LINE} rw nomodeset 3
}

menuentry "Reboot" { reboot }
menuentry "Power off" { halt }
EOF
success "GRUB installed."

# ---------------------------------------------------------------------------
# 5. Run the post-install hook (sets timezone, locale, optional user).
# ---------------------------------------------------------------------------
if [[ -x "${SCRIPT_DIR}/installer/post-install.sh" ]]; then
    log "Running post-install configuration…"
    bash "${SCRIPT_DIR}/installer/post-install.sh" \
        --root "${TARGET_MNT}" \
        --hostname "${DXN1_ROOT_LABEL}" || \
        warn "post-install.sh reported errors (continuing — install is otherwise complete)."
fi

sync
printf '%s\n' "$(date -Is)" > "${DXN1_STATE_DIR}/stage-06.done"
success "Stage 06 complete. ${DXN1_DISK} is now bootable."
